# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonathan/codeplex-rdmc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonathan/codeplex-rdmc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/codeplex-rdmc/CMakeFiles /home/jonathan/codeplex-rdmc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonathan/codeplex-rdmc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named verbs-mcast

# Build rule for target.
verbs-mcast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 verbs-mcast
.PHONY : verbs-mcast

# fast build rule for target.
verbs-mcast/fast:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/build
.PHONY : verbs-mcast/fast

connection.o: connection.cpp.o

.PHONY : connection.o

# target to build an object file
connection.cpp.o:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/connection.cpp.o
.PHONY : connection.cpp.o

connection.i: connection.cpp.i

.PHONY : connection.i

# target to preprocess a source file
connection.cpp.i:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/connection.cpp.i
.PHONY : connection.cpp.i

connection.s: connection.cpp.s

.PHONY : connection.s

# target to generate assembly for a file
connection.cpp.s:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/connection.cpp.s
.PHONY : connection.cpp.s

experiment.o: experiment.cpp.o

.PHONY : experiment.o

# target to build an object file
experiment.cpp.o:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/experiment.cpp.o
.PHONY : experiment.cpp.o

experiment.i: experiment.cpp.i

.PHONY : experiment.i

# target to preprocess a source file
experiment.cpp.i:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/experiment.cpp.i
.PHONY : experiment.cpp.i

experiment.s: experiment.cpp.s

.PHONY : experiment.s

# target to generate assembly for a file
experiment.cpp.s:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/experiment.cpp.s
.PHONY : experiment.cpp.s

group_send.o: group_send.cpp.o

.PHONY : group_send.o

# target to build an object file
group_send.cpp.o:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/group_send.cpp.o
.PHONY : group_send.cpp.o

group_send.i: group_send.cpp.i

.PHONY : group_send.i

# target to preprocess a source file
group_send.cpp.i:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/group_send.cpp.i
.PHONY : group_send.cpp.i

group_send.s: group_send.cpp.s

.PHONY : group_send.s

# target to generate assembly for a file
group_send.cpp.s:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/group_send.cpp.s
.PHONY : group_send.cpp.s

rdmc.o: rdmc.cpp.o

.PHONY : rdmc.o

# target to build an object file
rdmc.cpp.o:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/rdmc.cpp.o
.PHONY : rdmc.cpp.o

rdmc.i: rdmc.cpp.i

.PHONY : rdmc.i

# target to preprocess a source file
rdmc.cpp.i:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/rdmc.cpp.i
.PHONY : rdmc.cpp.i

rdmc.s: rdmc.cpp.s

.PHONY : rdmc.s

# target to generate assembly for a file
rdmc.cpp.s:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/rdmc.cpp.s
.PHONY : rdmc.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/util.cpp.s
.PHONY : util.cpp.s

verbs_helper.o: verbs_helper.cpp.o

.PHONY : verbs_helper.o

# target to build an object file
verbs_helper.cpp.o:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/verbs_helper.cpp.o
.PHONY : verbs_helper.cpp.o

verbs_helper.i: verbs_helper.cpp.i

.PHONY : verbs_helper.i

# target to preprocess a source file
verbs_helper.cpp.i:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/verbs_helper.cpp.i
.PHONY : verbs_helper.cpp.i

verbs_helper.s: verbs_helper.cpp.s

.PHONY : verbs_helper.s

# target to generate assembly for a file
verbs_helper.cpp.s:
	$(MAKE) -f CMakeFiles/verbs-mcast.dir/build.make CMakeFiles/verbs-mcast.dir/verbs_helper.cpp.s
.PHONY : verbs_helper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... format"
	@echo "... verbs-mcast"
	@echo "... connection.o"
	@echo "... connection.i"
	@echo "... connection.s"
	@echo "... experiment.o"
	@echo "... experiment.i"
	@echo "... experiment.s"
	@echo "... group_send.o"
	@echo "... group_send.i"
	@echo "... group_send.s"
	@echo "... rdmc.o"
	@echo "... rdmc.i"
	@echo "... rdmc.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... verbs_helper.o"
	@echo "... verbs_helper.i"
	@echo "... verbs_helper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

